# Generated by Django 4.1 on 2024-02-03 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='mood',
            field=models.CharField(choices=[('😊', 'Happy 😊'), ('😢', 'Sad 😢'), ('🤩', 'Excited 🤩'), ('😠', 'Angry 😠'), ('❤️', 'Love ❤️')], max_length=50),
        ),
    ]
