# Generated by Django 4.1 on 2024-02-22 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_featured_image_alter_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='mood',
            field=models.CharField(choices=[('😊', 'Happy 😊'), ('😢', 'Sad 😢'), ('🤩', 'Excited 🤩'), ('😠', 'Angry 😠'), ('❤️', 'Love ❤️'), ('😴', 'Sleepy 😴'), ('😮', 'Surprised 😮'), ('😕', 'Confused 😕'), ('😂', 'Laughing 😂'), ('😬', 'Nervous 😬')], default='😊', max_length=50),
        ),
    ]
