# Generated by Django 4.1 on 2024-02-22 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_draft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='draft',
        ),
    ]
